### ISSUE TITLE
admission_offset

### ISSUE THREAD

**Issue by ieee8023** [ml-workgroup/covid-19-image-repository#2]
I don't understand this field. It is the days since symptoms/admission?

For example patient 09ec853d with an admission_offset of -21 and an icu_admission_offset -20.0 ? So from this image they went to the ICU in 20 days and then were admitted to the hospital a day after?

**Comment by liob** [comment]
I amended the readme to include a description for the offset values. For this specific case, the patient was admitted 21 days before the image was taken and was admitted to the ICU 20 days ago. 

Especially the admission offset can be noisy. Some of the cases suggest that the admission to the clinic was after admission to the ICU. This is an artifact due to using the specific (COVID) case data for determining the admission date (and therefore offset). The patient may have already been at the ICU before being diagnosed with COVID.
